version: "3.9"
services:
  backend:
    build: ./apps/backend
    container_name: express-api-server
    command: sh -c "npx prisma. migrate deploy && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    container_name: next-app
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
      
volumes:
  db-data:
